cd /storage/mssnkt_grp/msrgxt/little/traj/T_0; sh lmp.sh
cd /storage/mssnkt_grp/msrgxt/little/traj/T_1; sh lmp.sh
cd /storage/mssnkt_grp/msrgxt/little/traj/T_2; sh lmp.sh
cd /storage/mssnkt_grp/msrgxt/little/traj/T_3; sh lmp.sh
cd /storage/mssnkt_grp/msrgxt/little/traj/T_4; sh lmp.sh
cd /storage/mssnkt_grp/msrgxt/little/traj/T_5; sh lmp.sh
cd /storage/mssnkt_grp/msrgxt/little/traj/T_6; sh lmp.sh
cd /storage/mssnkt_grp/msrgxt/little/traj/T_7; sh lmp.sh
cd /storage/mssnkt_grp/msrgxt/little/traj/T_8; sh lmp.sh
cd /storage/mssnkt_grp/msrgxt/little/traj/T_9; sh lmp.sh
