cd /storage/mssnkt_grp/msrgxt/thermo/Set_2/T_0; sh lmp.sh
cd /storage/mssnkt_grp/msrgxt/thermo/Set_2/T_1; sh lmp.sh
cd /storage/mssnkt_grp/msrgxt/thermo/Set_2/T_2; sh lmp.sh
cd /storage/mssnkt_grp/msrgxt/thermo/Set_2/T_3; sh lmp.sh
cd /storage/mssnkt_grp/msrgxt/thermo/Set_2/T_4; sh lmp.sh
cd /storage/mssnkt_grp/msrgxt/thermo/Set_2/T_5; sh lmp.sh
cd /storage/mssnkt_grp/msrgxt/thermo/Set_2/T_6; sh lmp.sh
cd /storage/mssnkt_grp/msrgxt/thermo/Set_2/T_7; sh lmp.sh
cd /storage/mssnkt_grp/msrgxt/thermo/Set_2/T_8; sh lmp.sh
cd /storage/mssnkt_grp/msrgxt/thermo/Set_2/T_9; sh lmp.sh
